### ISSUE TITLE
Inconsistency in Suit Icons Color Representation

### ISSUE THREAD

**Issue by kofaysi** [jdecked/twemoji#89] opened 2024-04-03 21:15 UTC
### Description
Encountered an issue within the twemoji library affecting the platform at BoardGamesGeek. There's a discrepancy in the color representation of the heart and diamond suit icons, which contradicts their expected appearance based on their names.

### Current Behavior
- Spade (:spades:) and club (:clubs:) icons display in black, as expected.
- Heart (:hearts:) and diamond (:diamonds:) icons display in red, conflicting with their "Black" prefix in naming.

### Expected Behavior
Option 1: Adjust the heart and diamond icons to display in black, aligning with their naming.
Option 2: Update the naming convention for these icons to reflect their color accurately if they are intended to remain red, to "Red Heart Suit" and "Red Diamond Suit."

### Steps to Reproduce
1. Use the twemoji library in a project.
2. Render the suit icons (:spades:, :clubs:, :hearts:, :diamonds:) following the library's guidelines.
3. Notice the color inconsistency among the icons.

### Expected Outcome
Uniform color representation for all suit icons or updated naming to accurately reflect their colors.

### Additional Context
The twemoji library's integration is crucial for BGG, and resolving this discrepancy will improve visual consistency and user experience.

### Links
- Emoji library: [twemoji](https://github.com/jdecked/twemoji)

Thank you for addressing this issue. Looking forward to a resolution.

**Comment by karptonite** [comment] 2024-04-03 21:58
Hi, to be be clear, the original poster is not making this request on behalf of BGG. Rather, he requested that BGG change the color, and we told him which library our Emoji's are derived from. BGG doesn't have any opinion on what color this should be.

**Comment by Crissov** [comment] 2024-04-03 22:38
Within Unicode character names, ” BLACK“ means _filled_ and ”WHITE“ means _hollow_. Twemoji has no influence on these immutable designations. 

Within Unicode (CLDR) emoji names, English color terms have their usual meaning. However, the four card suit emojis do not mention any color, i.e. they do not have to be represented in red and black, unlike the respective hearts, squares and circles. 

The submission window for emoji proposals to the Unicode consortium has just been opened again, so if anyone would like to request specific colored variants of the card suit emojis, e.g. green clubs and blue spades as ZWJ sequences with colored squares (♠️🟦, ♣️🟩, ♦️🟨, ♥️⬛️), now would be the perfect time to do so, although I’d consider the chances of them being accepted to be rather slim.

**Comment by jdecked** [comment] 2024-04-03 23:14
I believe this issue has been sufficiently addressed by the above two comments. We won't be changing the colour of this specific emoji; they display as intended.

(Also, BGG rocks! Thanks for working on it Daniel!)

**Closed by jdecked** 2024-04-03 23:14 UTC
Labels: wontfix
