### ISSUE TITLE
Flag of Sark (CQ)

### ISSUE THREAD

**Issue by xDEADC0DE** [jdecked/twemoji#105] opened 2024-07-22 08:04 UTC
If someone wants to create the flag for Sark (code `CQ`, new in Emoji 16,0ß), notice that there are two possible designs, wether the two lion cover the Saint George cross or not.

The one with the bigger lions is from 1938 and was designed for the island’s *seigneur* before becoming the defacto symbol of the island. In 2020 the flag was officialized but the College of Arms petition featured a design with the lions kept in the canton.

Wikipedia puts the new design as the official flag, but it seems that the locals prefer the original design (from what I’ve read), as does the British Flag Institute: https://www.flaginstitute.org/wp/flags/sark-flag/

**Comment by jdecked** [comment] 2024-07-28 04:33
Duplicate of #88 

Thanks for pointing this out! In the future, please keep Unicode 16 discussion to the relevant issue. I've copied the text of this issue and tagged you over there; respond there for any future discussion.

**Closed by jdecked** 2024-07-28 04:33 UTC
